# /rg flag -w "{world_name}" -h 6 {region_name} deny-back ALLOW

# what commands to deny
deny-commands:
  - '/back'
  - '/cmi back'
  - '/eback'
  - '/cback'
  - '/cmi cback'
  - '/return'
  - '/ereturn'
  - '/dback'

# the permission that allows players to /back to their death location
back-on-death-permission: 'essentials.back.ondeath' # cmi.command.back.ondeath for cmi

# if GriefPrevention is enabled, true = /back will be denied if a player's last known location is inside a claim they are not trusted in
deny-untrusted-claims: true

# set this true to deny back to all non-members of a region - setting the region flag overrides this
deny-nonmembers: false

# message sent to player if they are denied returning to a location
deny-message: '&c&lHey! &7Sorry, but you can''t return to there.'
# this will use GriefPrevention's message when a player tries to return to a claim
use-grief-prevention-message: true

# How often the plugin saves while the server is running in minutes - 0 to disable
auto-save-interval: 0

back-command:
  # register a back command for DenyBack
  register: false
  # send player back to the last location that they are allowed to go
  use-last-available-location: true
  # how many seconds before player will be teleported
  teleport-delay: 0
  # message sent to player when they use the command
  message: '&6Returning to previous location.'