name: DenyBack
version: 1.9
main: me.jadenp.denyback.Denyback
api-version: 1.13
depend: [ WorldGuard ]
softdepend:
  - GriefPrevention
authors: [ Not_Jaden ]
description: Option to disable /back into a WorldGuard region or GriefPrevention Claims
commands:
  denyback:
    usage: /denyback
    description: used to reload the config
  dback:
    usage: /dback
    description: built in back command
    permission: denyback.back
permissions:
  denyback.admin:
    description: to be able to reload the config
    default: op
    children: [denyback.back, denyback.back.ondeath]
  denyback.back:
    description: use /back if enabled
    default: false
  denyback.back.ondeath:
    description: use /back on death
    default: false
