name: DenyBack
version: ${project.version}
main: me.jadenp.denyback.Denyback
api-version: 1.13
depend: [ WorldGuard ]
softdepend:
  - GriefPrevention
authors: [ Not_Jaden ]
description: Option to disable /back into a WorldGuard region or GriefPrevention Claims
commands:
  denyback:
    usage: /denyback
    description: used to reload the config
permissions:
  denyback.admin:
    description: to be able to reload the config
    default: op
  denyback.back:
    description: use /back if enabled
    default: false
  denyback.back.ondeath:
    description: use /back on death
    default: false
